;; Some tests for catch & throw.

(def (foo)
     (print "In foo\n")
     (throw foo-exception)
     (print "This shouldn't be reached\n"))

(catch (do (foo)
	   (print "This shouldn't be reached\n"))
       foo-exception
       (print "Caught foo-exception\n"))

(def (bar x)
     (print "In bar, x = " x "\n")
     (if (> x 4)
	 (throw bar-exception)
	 (fib x)))

(def (fib x)
     (if (< x 2)
	 1
	 (+ (fib (- x 1))
	    (catch (bar (- x 2))
		   bar-exception
		   (fib (- x 2))))))

(print (fib 10) "\n")
